eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
server:
  port: 9000


logging:
  level:
    org.springframework.web: INFO
